#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import print_function

__version__   = 'version 0.2'
__author__    = 'Marcin Sztolcman <marcin@urzenia.net>'
__copyright__ = '(r) 2012'
__program__   = 'b64 - encode/decode b64 data in the fly'
__date__      = '2012-12-22'
__license__   = 'GPL v.2'

__desc__      = '''%(desc)s
%(author)s %(copyright)s
license: %(license)s
version %(version)s (%(date)s)''' % {
  'desc': __program__,
  'author': __author__,
  'copyright': __copyright__,
  'license': __license__,
  'version': __version__,
  'date': __date__
}

import base64
import getopt
import os.path
import sys

def usage ():
    print (
        "%s [-f] [-l path] [-h] [-v] [data]\n"
        "-f - decode from base64 (otherwise - encode to base64)\n"
        "-l path - encode/decode path, if [data] is missing\n"
        "-h - this help\n"
        "-v - version"
            % os.path.basename (sys.argv[0])
    )

if __name__ == '__main__':
    direction = 'to'
    file_ = None
    opts, args = getopt.gnu_getopt (sys.argv[1:], 'fthvl:')
    for o, a in opts:
        if o == '-f':
            direction = 'from'
        elif o == '-l':
            file_ = a
        elif o == '-h':
            usage ()
            sys.exit (0);
        elif o == '-v':
            print (__desc__)
            sys.exit (0)

    if direction == 'to':
        func = base64.b64encode
    else:
        func = base64.b64decode

    if file_ == '-' or (file_ is None and not args):
        body = sys.stdin.read ()
    elif args:
        body = args[0]
    else:
        body = open (file_, 'r').read ()

    print (func (body))

# vim: ft=python
