#!/usr/bin/env python2.6

from __future__ import print_function

__version__   = 'version 0.1'
__author__    = 'Marcin Sztolcman <marcin@urzenia.net>'
__copyright__ = '(r) 2012'
__program__   = 'b64 - encode/decode b64 data in the fly'
__date__      = '2012-07-13'
__license__   = 'GPL v.2'

__desc__      = '''%(desc)s
%(author)s %(copyright)s
license: %(license)s
version %(version)s (%(date)s)''' % {
  'desc': __program__,
  'author': __author__,
  'copyright': __copyright__,
  'license': __license__,
  'version': __version__,
  'date': __date__
}

import base64
import getopt
import sys

if __name__ == '__main__':
    direction = 'to'
    file_ = '-'
    opts, args = getopt.gnu_getopt (sys.argv[1:], 'ft')
    for o, a in opts:
        if o == '-f':
            direction = 'from'

    if args:
        file_ = args[0]

    if direction == 'to':
        func = base64.b64encode
    else:
        func = base64.b64decode

    if file_ == '-':
        body = sys.stdin.read ()
    else:
        body = open (file_, 'r').read ()

    print (func (body))

# vim: ft=python
